// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DashbordGrad.Models;

public partial class City
{
    public int Id { get; set; }

    public string Name { get; set; }

    public virtual ICollection<Bank> Banks { get; set; } = new List<Bank>();

    public virtual ICollection<Embass> Embasses { get; set; } = new List<Embass>();

    public virtual ICollection<EntertainmentPlace> EntertainmentPlaces { get; set; } = new List<EntertainmentPlace>();

    public virtual ICollection<Hotel> Hotels { get; set; } = new List<Hotel>();

    public virtual ICollection<Restaurant> Restaurants { get; set; } = new List<Restaurant>();

    public virtual ICollection<TourismtPlace> TourismtPlaces { get; set; } = new List<TourismtPlace>();

    public virtual ICollection<TransportProvider> TransportProviders { get; set; } = new List<TransportProvider>();
}