// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DashbordGrad.Models;

public partial class EntertainmentPlace
{
    public int Id { get; set; }

    public string Name { get; set; }

    public int OpiningHour { get; set; }

    public string PlaceType { get; set; }

    public string ContactInfo { get; set; }

    public string Longitude { get; set; }

    public string Latitude { get; set; }

    public int CityId { get; set; }

    public virtual City City { get; set; }
}