// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DashbordGrad.Models;

public partial class TourismtPlace
{
    public int Id { get; set; }

    public string Name { get; set; }

    public string Discription { get; set; }

    public float? TicketPrice { get; set; }

    public string Image { get; set; }

    public int? Rating { get; set; }

    public string Longitude { get; set; }

    public string Latitude { get; set; }

    public int CityId { get; set; }

    public int Typeofplaceid { get; set; }

    public virtual City City { get; set; }

    public virtual Type Typeofplace { get; set; }
}