// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DashbordGrad.Models;

public partial class Type
{
    public int Id { get; set; }

    public string Name { get; set; }

    public virtual ICollection<TourismtPlace> TourismtPlaces { get; set; } = new List<TourismtPlace>();

    public virtual ICollection<TransportProvider> TransportProviders { get; set; } = new List<TransportProvider>();
}