// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DashbordGrad.Models;

public partial class User
{
    public int Id { get; set; }

    public string FirstName { get; set; }

    public string SacondName { get; set; }

    public DateTime Bdate { get; set; }

    public string Password { get; set; }

    public string Email { get; set; }

    public string BackgroundPhoto { get; set; }

    public string City { get; set; }
}